language: node_js
node_js:
  - "node"

sudo: required

services:
  - docker
  
before_install:
  - docker build -t sfz-inc/hello-react .

notifications:
  webhooks:
    urls:
      - https://webhook.atomist.com/atomist/travis/teams/T489LV5QF
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
